#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MATS.OA;


namespace MATS.OA	
{
	public partial class Address
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this._country;
		    }
		    set
		    {
		        this._country = value;
		    }
		}
		
		private string _city;
		public virtual string City 
		{ 
		    get
		    {
		        return this._city;
		    }
		    set
		    {
		        this._city = value;
		    }
		}
		
		private string _streetAddress;
		public virtual string StreetAddress 
		{ 
		    get
		    {
		        return this._streetAddress;
		    }
		    set
		    {
		        this._streetAddress = value;
		    }
		}
		
		private string _subCity;
		public virtual string SubCity 
		{ 
		    get
		    {
		        return this._subCity;
		    }
		    set
		    {
		        this._subCity = value;
		    }
		}
		
		private string _kebele;
		public virtual string Kebele 
		{ 
		    get
		    {
		        return this._kebele;
		    }
		    set
		    {
		        this._kebele = value;
		    }
		}
		
		private string _houseNumber;
		public virtual string HouseNumber 
		{ 
		    get
		    {
		        return this._houseNumber;
		    }
		    set
		    {
		        this._houseNumber = value;
		    }
		}
		
		private string _telephone;
		public virtual string Telephone 
		{ 
		    get
		    {
		        return this._telephone;
		    }
		    set
		    {
		        this._telephone = value;
		    }
		}
		
		private string _mobile;
		public virtual string Mobile 
		{ 
		    get
		    {
		        return this._mobile;
		    }
		    set
		    {
		        this._mobile = value;
		    }
		}
		
		private string _poBox;
		public virtual string PoBox 
		{ 
		    get
		    {
		        return this._poBox;
		    }
		    set
		    {
		        this._poBox = value;
		    }
		}
		
		private string _fax;
		public virtual string Fax 
		{ 
		    get
		    {
		        return this._fax;
		    }
		    set
		    {
		        this._fax = value;
		    }
		}
		
		private string _primaryEmail;
		public virtual string PrimaryEmail 
		{ 
		    get
		    {
		        return this._primaryEmail;
		    }
		    set
		    {
		        this._primaryEmail = value;
		    }
		}
		
		private string _alternateEmail;
		public virtual string AlternateEmail 
		{ 
		    get
		    {
		        return this._alternateEmail;
		    }
		    set
		    {
		        this._alternateEmail = value;
		    }
		}
		
		private int _enabled;
		public virtual int Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int? _createdByUserId;
		public virtual int? CreatedByUserId 
		{ 
		    get
		    {
		        return this._createdByUserId;
		    }
		    set
		    {
		        this._createdByUserId = value;
		    }
		}
		
		private DateTime? _dateRecordCreated;
		public virtual DateTime? DateRecordCreated 
		{ 
		    get
		    {
		        return this._dateRecordCreated;
		    }
		    set
		    {
		        this._dateRecordCreated = value;
		    }
		}
		
		private int? _modifiedByUserId;
		public virtual int? ModifiedByUserId 
		{ 
		    get
		    {
		        return this._modifiedByUserId;
		    }
		    set
		    {
		        this._modifiedByUserId = value;
		    }
		}
		
		private DateTime? _dateLastModified;
		public virtual DateTime? DateLastModified 
		{ 
		    get
		    {
		        return this._dateLastModified;
		    }
		    set
		    {
		        this._dateLastModified = value;
		    }
		}
		
		private IList<Contact> _contacts = new List<Contact>();
		public virtual IList<Contact> Contacts 
		{ 
		    get
		    {
		        return this._contacts;
		    }
		}
		
		private IList<Client> _clients = new List<Client>();
		public virtual IList<Client> Clients 
		{ 
		    get
		    {
		        return this._clients;
		    }
		}
		
	}
}
