#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MATS.OA;


namespace MATS.OA	
{
	public partial class Attachment
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _attachmentName;
		public virtual string AttachmentName 
		{ 
		    get
		    {
		        return this._attachmentName;
		    }
		    set
		    {
		        this._attachmentName = value;
		    }
		}
		
		private int _ticketId;
		public virtual int TicketId 
		{ 
		    get
		    {
		        return this._ticketId;
		    }
		    set
		    {
		        this._ticketId = value;
		    }
		}
		
		private int _enabled;
		public virtual int Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int? _createdByUserId;
		public virtual int? CreatedByUserId 
		{ 
		    get
		    {
		        return this._createdByUserId;
		    }
		    set
		    {
		        this._createdByUserId = value;
		    }
		}
		
		private DateTime? _dateRecordCreated;
		public virtual DateTime? DateRecordCreated 
		{ 
		    get
		    {
		        return this._dateRecordCreated;
		    }
		    set
		    {
		        this._dateRecordCreated = value;
		    }
		}
		
		private int? _modifiedByUserId;
		public virtual int? ModifiedByUserId 
		{ 
		    get
		    {
		        return this._modifiedByUserId;
		    }
		    set
		    {
		        this._modifiedByUserId = value;
		    }
		}
		
		private DateTime? _dateLastModified;
		public virtual DateTime? DateLastModified 
		{ 
		    get
		    {
		        return this._dateLastModified;
		    }
		    set
		    {
		        this._dateLastModified = value;
		    }
		}
		
		private int _attachmentStatus;
		public virtual int AttachmentStatus 
		{ 
		    get
		    {
		        return this._attachmentStatus;
		    }
		    set
		    {
		        this._attachmentStatus = value;
		    }
		}
		
		private Ticket _ticket;
		public virtual Ticket Ticket 
		{ 
		    get
		    {
		        return this._ticket;
		    }
		    set
		    {
		        this._ticket = value;
		    }
		}
		
	}
}
