#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MATS.OA;


namespace MATS.OA	
{
	public partial class MATSServerDbContext : OpenAccessContext, IMATSServerDbContextUnitOfWork
	{
		private static string connectionStringName = @"MatsDbConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
	
		public MATSServerDbContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public MATSServerDbContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public MATSServerDbContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public MATSServerDbContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public MATSServerDbContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<User> Users 
		{
	    	get
	    	{
	        	return this.GetAll<User>();
	    	}
		}
		
		public IQueryable<Ticket> Tickets 
		{
	    	get
	    	{
	        	return this.GetAll<Ticket>();
	    	}
		}
		
		public IQueryable<Role> Roles 
		{
	    	get
	    	{
	        	return this.GetAll<Role>();
	    	}
		}
		
		public IQueryable<Remark> Remarks 
		{
	    	get
	    	{
	        	return this.GetAll<Remark>();
	    	}
		}
		
		public IQueryable<ProductActivation> ProductActivations 
		{
	    	get
	    	{
	        	return this.GetAll<ProductActivation>();
	    	}
		}
		
		public IQueryable<PaymentDTO> PaymentDTOs 
		{
	    	get
	    	{
	        	return this.GetAll<PaymentDTO>();
	    	}
		}
		
		public IQueryable<List> Lists 
		{
	    	get
	    	{
	        	return this.GetAll<List>();
	    	}
		}
		
		public IQueryable<Contact> Contacts 
		{
	    	get
	    	{
	        	return this.GetAll<Contact>();
	    	}
		}
		
		public IQueryable<Client> Clients 
		{
	    	get
	    	{
	        	return this.GetAll<Client>();
	    	}
		}
		
		public IQueryable<Attachment> Attachments 
		{
	    	get
	    	{
	        	return this.GetAll<Attachment>();
	    	}
		}
		
		public IQueryable<Address> Addresses 
		{
	    	get
	    	{
	        	return this.GetAll<Address>();
	    	}
		}
		
		public IQueryable<__MigrationHistory> __MigrationHistories 
		{
	    	get
	    	{
	        	return this.GetAll<__MigrationHistory>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}

	public interface IMATSServerDbContextUnitOfWork : IUnitOfWork
	{
		IQueryable<User> Users 
		{ 
			get;
		}

		IQueryable<Ticket> Tickets 
		{ 
			get;
		}

		IQueryable<Role> Roles 
		{ 
			get;
		}

		IQueryable<Remark> Remarks 
		{ 
			get;
		}

		IQueryable<ProductActivation> ProductActivations 
		{ 
			get;
		}

		IQueryable<PaymentDTO> PaymentDTOs 
		{ 
			get;
		}

		IQueryable<List> Lists 
		{ 
			get;
		}

		IQueryable<Contact> Contacts 
		{ 
			get;
		}

		IQueryable<Client> Clients 
		{ 
			get;
		}

		IQueryable<Attachment> Attachments 
		{ 
			get;
		}

		IQueryable<Address> Addresses 
		{ 
			get;
		}

		IQueryable<__MigrationHistory> __MigrationHistories 
		{ 
			get;
		}

	}
}
#pragma warning restore 1591

