#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace MATS.OA	
{
	public partial class ProductActivation
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _productKey;
		public virtual string ProductKey 
		{ 
		    get
		    {
		        return this._productKey;
		    }
		    set
		    {
		        this._productKey = value;
		    }
		}
		
		private string _licensedTo;
		public virtual string LicensedTo 
		{ 
		    get
		    {
		        return this._licensedTo;
		    }
		    set
		    {
		        this._licensedTo = value;
		    }
		}
		
		private DateTime _activatedDate;
		public virtual DateTime ActivatedDate 
		{ 
		    get
		    {
		        return this._activatedDate;
		    }
		    set
		    {
		        this._activatedDate = value;
		    }
		}
		
		private DateTime _expirationDate;
		public virtual DateTime ExpirationDate 
		{ 
		    get
		    {
		        return this._expirationDate;
		    }
		    set
		    {
		        this._expirationDate = value;
		    }
		}
		
		private string _registeredBIOS_SN;
		public virtual string RegisteredBIOS_SN 
		{ 
		    get
		    {
		        return this._registeredBIOS_SN;
		    }
		    set
		    {
		        this._registeredBIOS_SN = value;
		    }
		}
		
		private int _enabled;
		public virtual int Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int? _createdByUserId;
		public virtual int? CreatedByUserId 
		{ 
		    get
		    {
		        return this._createdByUserId;
		    }
		    set
		    {
		        this._createdByUserId = value;
		    }
		}
		
		private DateTime? _dateRecordCreated;
		public virtual DateTime? DateRecordCreated 
		{ 
		    get
		    {
		        return this._dateRecordCreated;
		    }
		    set
		    {
		        this._dateRecordCreated = value;
		    }
		}
		
		private int? _modifiedByUserId;
		public virtual int? ModifiedByUserId 
		{ 
		    get
		    {
		        return this._modifiedByUserId;
		    }
		    set
		    {
		        this._modifiedByUserId = value;
		    }
		}
		
		private DateTime? _dateLastModified;
		public virtual DateTime? DateLastModified 
		{ 
		    get
		    {
		        return this._dateLastModified;
		    }
		    set
		    {
		        this._dateLastModified = value;
		    }
		}
		
		private int _clientId;
		public virtual int ClientId 
		{ 
		    get
		    {
		        return this._clientId;
		    }
		    set
		    {
		        this._clientId = value;
		    }
		}
		
	}
}
